FROM ubuntu:latest
MAINTAINER drew.moseley@toradex.com
ENV DEBIAN_FRONTEND noninteractive
RUN apt update
RUN apt -y install apt-utils
RUN apt -y dist-upgrade
RUN apt -y install nginx
RUN apt -y install bc
RUN apt -y install build-essential
CMD ["echo","Docker Image Size Test"]
